# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da5e45042820af70dc73622a10ddf86a5af82abfea1d4a092852b622e4858b806f6b1b2ea34829d620564705db7d018299c2b02b2f1825f77993a3352d94d7e7

test:
  secret_key_base: 97bbe8025b3e84630c029088005bfcdac9d093768283d76050068b8497e31dc78852c06c9c0d8a118a0551f0d380193b49d5cb42523628f5a88112bbfd9ee933

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
